# Generated by Django 5.2.5 on 2025-08-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UCalendarEvent',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('TENTATIVE', 'Tentative'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=16)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=8)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='f_user.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='f_user.user')),
            ],
            options={
                'db_table': 'u_calendar_event',
            },
        ),
        migrations.CreateModel(
            name='UEventAttendees',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('response_status', models.CharField(choices=[('NEEDS_ACTION', 'Needs Action'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TENTATIVE', 'Tentative')], default='NEEDS_ACTION', max_length=16)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_events', to='f_user.user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='f_calendar.ucalendarevent')),
            ],
            options={
                'db_table': 'u_event_attendees',
            },
        ),
    ]
