# Generated by Django 5.2.5 on 2025-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercorporate',
            name='asset_turnover',
        ),
        migrations.RemoveField(
            model_name='customercorporate',
            name='current_ratio',
        ),
        migrations.RemoveField(
            model_name='customercorporate',
            name='debt_ratio',
        ),
        migrations.RemoveField(
            model_name='customercorporate',
            name='equity_ratio',
        ),
        migrations.RemoveField(
            model_name='customercorporate',
            name='equity_to_debt_ratio',
        ),
        migrations.RemoveField(
            model_name='customercorporate',
            name='long_term_debt_to_equity_ratio',
        ),
        migrations.RemoveField(
            model_name='customercorporate',
            name='net_profit_margin',
        ),
        migrations.RemoveField(
            model_name='customercorporate',
            name='operating_margin',
        ),
        migrations.RemoveField(
            model_name='customercorporate',
            name='operating_roa',
        ),
        migrations.RemoveField(
            model_name='customercorporate',
            name='quick_ratio',
        ),
        migrations.RemoveField(
            model_name='customercorporate',
            name='roa',
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='cost_of_goods_sold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='current_assets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='depreciation_amortization',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='ebit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='ebitda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='inventory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='net_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='net_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='retained_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='total_assets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='total_current_liabilities',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='total_liabilities',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='total_long_term_debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='total_operating_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='total_receivables',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='customercorporate',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
