# Generated by Django 5.2.5 on 2025-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_customer', '0002_remove_customercorporate_asset_turnover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercorporate',
            name='company_name',
            field=models.CharField(default='Default Company Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='customercorporate',
            name='legal_name',
            field=models.CharField(max_length=255),
        ),
    ]
