# Generated by Django 5.2.5 on 2025-09-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_customer', '0003_customercorporate_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerperson',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
