# Generated by Django 5.2.5 on 2025-09-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_customer', '0004_customerperson_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercorporate',
            name='depreciation_amortization',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customercorporate',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customercorporate',
            name='total_long_term_debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customercorporate',
            name='total_receivables',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
