# Generated by Django 5.2.5 on 2025-08-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f_customer', '0001_initial'),
        ('f_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAssessment',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_type', models.CharField(default='INDIVIDUAL', max_length=16)),
                ('product_type', models.CharField(default='CREDIT_LOAN', max_length=16)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('requested_term', models.IntegerField()),
                ('purpose', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='f_user.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_customer.customer')),
            ],
            options={
                'db_table': 'loan_assessment',
            },
        ),
    ]
