# Generated by Django 5.2.5 on 2025-09-18 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('CREDIT_LOAN', 'Credit Loan'), ('MORTGAGE_LOAN', 'Mortgage Loan'), ('CAR_LOAN', 'Car Loan'), ('HOUSING_LOAN', 'Housing Loan'), ('BUSINESS_LOAN', 'Business Loan')], default='CREDIT_LOAN', max_length=32)),
                ('min_rate_bp', models.IntegerField()),
                ('max_rate_bp', models.IntegerField()),
                ('min_limit_krw', models.DecimalField(decimal_places=0, max_digits=18)),
                ('max_limit_krw', models.DecimalField(decimal_places=0, max_digits=18)),
                ('max_term_months', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanAssessmentStep',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('DISBURSED', 'Disbursed')], default='SUBMITTED', max_length=16)),
                ('decision', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'Other')], null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_loan.loanassessment')),
            ],
            options={
                'db_table': 'loan_assessment_steps',
            },
        ),
    ]
