# Generated by Django 5.2.5 on 2025-09-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_loan', '0002_loanproduct_loanassessmentstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanassessment',
            name='purpose',
            field=models.CharField(choices=[('EDUCATION', 'Education'), ('MEDICAL', 'Medical'), ('VENTURE', 'Venture'), ('PERSONAL', 'Personal'), ('DEBTCONSOLIDATION', 'Debtconsolidation')], default='PERSONAL', max_length=32),
        ),
    ]
