# Generated by Django 5.2.5 on 2025-08-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate')], default='INDIVIDUAL', max_length=16)),
                ('display_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='ACTIVE', max_length=16)),
                ('risk_segment', models.CharField(default='RETAIL', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_common.uncbanklocation')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerCorporate',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='corporate', serialize=False, to='f_customer.customer')),
                ('legal_name', models.CharField(max_length=255, unique=True)),
                ('biz_reg_no_masked', models.CharField(max_length=64, unique=True)),
                ('incorporation_date', models.DateField()),
                ('employees_count', models.IntegerField()),
                ('mobile', models.CharField(max_length=32)),
                ('roa', models.DecimalField(decimal_places=4, max_digits=10)),
                ('net_profit_margin', models.DecimalField(decimal_places=4, max_digits=10)),
                ('operating_roa', models.DecimalField(decimal_places=4, max_digits=10)),
                ('operating_margin', models.DecimalField(decimal_places=4, max_digits=10)),
                ('current_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quick_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('debt_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('equity_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('equity_to_debt_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('long_term_debt_to_equity_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('asset_turnover', models.DecimalField(decimal_places=4, max_digits=10)),
                ('industry_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_common.cindustrycode')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPerson',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to='f_customer.customer')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('gender', models.PositiveSmallIntegerField()),
                ('rrn', models.CharField(max_length=64, unique=True)),
                ('mobile', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('account_number', models.CharField(max_length=64)),
                ('account_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('income_annual', models.DecimalField(decimal_places=2, max_digits=18)),
                ('work_experience_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_delinquency', models.BooleanField(default=False)),
                ('credit_history_length', models.IntegerField(default=0)),
                ('credit_rating', models.PositiveSmallIntegerField()),
                ('education_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_common.ceducationlevel')),
                ('employment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_common.uncemploymenttype')),
                ('housing_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_common.chousingstatus')),
                ('industry_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_common.cindustrycode')),
            ],
            options={
                'db_table': 'customer_person',
            },
        ),
    ]
