# Generated by Django 5.2.5 on 2025-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceducationlevel',
            name='sort_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ceducationlevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
