# Generated by Django 5.2.5 on 2025-09-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_common', '0002_ceducationlevel_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceducationlevel',
            name='name',
            field=models.CharField(choices=[('HIGH_SCHOOL', 'High School'), ('ASSOCIATE', 'Associate'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('DOCTORATE', 'Doctorate')], default='HIGH_SCHOOL', max_length=16),
        ),
        migrations.AlterField(
            model_name='chousingstatus',
            name='name',
            field=models.CharField(choices=[('RENT', 'Rent'), ('MORTGAGE', 'Mortgage'), ('OWN', 'Own'), ('OTHER', 'Other')], default='OWN', max_length=16),
        ),
    ]
