# Generated by Django 5.0.6 on 2024-05-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_common', '0002_ceducationlevel_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceducationlevel',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='chousingstatus',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]