# Generated by Django 5.2.5 on 2025-08-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=512)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('doc_type', models.CharField(choices=[('PDF', 'Pdf'), ('REPORT', 'Report')], default='PDF', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='f_user.user')),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentBinding',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bind_type', models.CharField(choices=[('CHAT', 'Chat'), ('REVIEW', 'Review')], max_length=16)),
                ('bind_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='f_document.document')),
            ],
            options={
                'db_table': 'document_binding',
            },
        ),
    ]
