# Generated by Django 5.2.5 on 2025-08-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotRetrivalEvent',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('retriever', models.CharField(max_length=64)),
                ('query_text', models.TextField()),
                ('k', models.IntegerField(default=5)),
                ('score_type', models.CharField(default='cosine', max_length=32)),
                ('latency_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chatbot_retrival_event',
            },
        ),
        migrations.CreateModel(
            name='ChatbotRetrievedChunk',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('doc_id', models.CharField(max_length=255)),
                ('chunk_id', models.CharField(max_length=255)),
                ('score', models.FloatField(blank=True, null=True)),
                ('used_in_context', models.BooleanField(default=False)),
                ('retriever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='f_chatbot.chatbotretrivalevent')),
            ],
            options={
                'db_table': 'chatbot_retrieved_chunk',
            },
        ),
        migrations.CreateModel(
            name='UChatbotHistory',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_user.user')),
            ],
            options={
                'db_table': 'u_chatbot_history',
            },
        ),
        migrations.CreateModel(
            name='UChatbotSession',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_from', models.CharField(choices=[('AI', 'Ai'), ('USER', 'User')], default='USER', max_length=8)),
                ('content', models.CharField(max_length=4000)),
                ('sent_at', models.DateTimeField()),
                ('chatbot_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='f_chatbot.uchatbothistory')),
            ],
            options={
                'db_table': 'u_chatbot_session',
            },
        ),
        migrations.AddField(
            model_name='chatbotretrivalevent',
            name='session_msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_events', to='f_chatbot.uchatbotsession'),
        ),
    ]
