# Generated by Django 5.2.5 on 2025-08-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UDepartment',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'u_department',
            },
        ),
        migrations.CreateModel(
            name='UPosition',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'u_position',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('ext_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('ON_DUTY', 'On Duty'), ('ON_LEAVE', 'On Leave'), ('RESIGNED', 'Resigned')], default='ON_DUTY', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_common.uncbanklocation')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_user.udepartment')),
                ('employment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_common.uncemploymenttype')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='f_user.user')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_user.uposition')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
