# Generated by Django 5.2.5 on 2025-08-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTodoList',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_user.user')),
            ],
            options={
                'db_table': 'u_todo_list',
            },
        ),
    ]
