# Generated by Django 5.2.5 on 2025-09-25 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_chatbot', '0001_initial'),
        ('f_document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotPDFReference',
            fields=[
                ('seq_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_references', to='f_document.document')),
                ('session_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_references', to='f_chatbot.uchatbotsession')),
            ],
            options={
                'db_table': 'chatbot_pdf_reference',
                'indexes': [models.Index(fields=['session_msg'], name='chatbot_pdf_session_27ea27_idx'), models.Index(fields=['document'], name='chatbot_pdf_documen_2158f1_idx')],
            },
        ),
    ]
