# Generated by Django 5.2.5 on 2025-09-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_chatbot', '0002_chatbotpdfreference'),
        ('f_document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotpdfreference',
            name='file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='chatbotpdfreference',
            name='item_type',
            field=models.CharField(choices=[('CURRENT_PDF', 'Current Pdf'), ('REFERENCE', 'Reference')], default='REFERENCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatbotpdfreference',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_references', to='f_document.document'),
        ),
    ]
