name: Django CICD App

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  build-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:latest

      - name: Set Elastic Beanstalk version label
        id: eb_version
        run: |
          VERSION="app-${GITHUB_SHA}-$(date +%Y%m%d%H%M%S)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
          region: ap-northeast-2
          version_label: ${{ env.VERSION }}
          deployment_package: Dockerrun.aws.json
          bucket_name: "elasticbeanstalk-ap-northeast-2-${{ github.repository }}-${{ github.run_id }}"
          key: "${{ env.VERSION }}.zip"
          skip_existing: true
